name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.AI_HF_TOKEN }}
        run: |
          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/ze19n/sow-smart-backend
          git push hf main --force